Include code from PEP302 loaders in tracebacks
zopefoundation/zope.exceptions pull request #33
Opened 2024-05-24 04:59 UTC by perrinjerome

Since cpython commit 6bc2c1e7eb , included since python 3.5, `linecache` module exposes a new `lazycache` function that needs to be called to capture information for modules not based on files.

The tests are based on zipimport, because it's a simple and realistic way of using such a loader.

2024-05-24 06:44 UTC, icemac requested changes
I like the changes and have only one suggestion.

2024-05-24 06:44 UTC, icemac commented on src/zope/exceptions/tests/test_exceptionformatter.py
> +""")
```suggestion
                    textwrap.dedent("""
                        def f():
                            1 / 0
                    """)
```
This improves readability but additionally requires to import `textwrap`.

2024-05-24 09:30 UTC, perrinjerome commented on src/zope/exceptions/tests/test_exceptionformatter.py
> +""")
Thank you, I have applied this and changed another place where `textwrap` was imported locally in the test function to make it a global import.

2024-06-07 06:24 UTC, icemac approved these changes

2024-06-07 06:24 UTC, merged

2024-06-07 06:27 UTC, icemac commented
Released in https://pypi.org/project/zope.exceptions/5.1/.

2024-06-07 15:36 UTC, perrinjerome commented
Thank you @icemac